const API="/api";let token=localStorage.getItem("mpce_token")||"";let me=null;let organs=[];let officeMap=new Map();
const $=s=>document.querySelector(s);const headers=()=>token?{"Authorization":"Bearer "+token}:{};const api=async(url,opt={})=>{const r=await fetch(API+url,{...opt,headers:{...headers(),...(opt.headers||{})}});if(!r.ok){let d;try{d=await r.json()}catch{d={detail:r.statusText}};throw new Error(typeof d.detail==="string"?d.detail:JSON.stringify(d.detail))}return r.json()};
const fmt=d=>new Date(d+"T00:00:00").toLocaleDateString("pt-BR");

async function loadPublic(){const y=$("#publicYear").value;const rows=await fetch(API+"/public/dashboard?year="+y).then(r=>r.json());$("#publicStats").innerHTML=[
["Sessões",rows.length],["Órgãos",new Set(rows.map(x=>x.organ)).size],["Substituições",rows.filter(x=>x.status==="substitution").length],["Pendências",rows.filter(x=>x.status.startsWith("pending")).length]
].map(x=>`<div class="card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");
$("#publicTable").innerHTML=`<table><thead><tr><th>Data</th><th>Órgão</th><th>Procuradoria nominal</th><th>Atuação efetiva</th><th>Situação</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmt(r.date)}</td><td>${r.organ}</td><td>${r.nominal_office}</td><td>${r.effective_office||"Pendente"}</td><td>${r.status}</td></tr>`).join("")}</tbody></table>`}

async function bootAdmin(){if(!token)return;try{me=await api("/me");organs=await api("/organs");officeMap=new Map();organs.forEach(o=>o.offices.forEach(x=>officeMap.set(x.id,x)));$("#login").hidden=true;$("#admin").hidden=false;$("#logout").hidden=false;$("#identity").textContent=`Usuário: ${me.username} • Perfil: ${me.role}`;fillSelects();await Promise.all([loadVacations(),loadSessions(),loadSubs(),loadSchedule()]);if(me.role==="admin"){loadAudit();loadUsers()}else{$('[data-tab="users"]').hidden=true;$('[data-tab="audit"]').hidden=true}if(me.role==="viewer"){["#vacForm","#sessionForm","#subForm","#generateYear"].forEach(id=>{if($(id))$(id).hidden=true})}}catch{localStorage.removeItem("mpce_token");token=""}}
function fillSelects(){const offices=[...officeMap.entries()].sort((a,b)=>parseInt(a[1].number)-parseInt(b[1].number));["#vacOffice","#sessionOffice","#subOffice","#substituteOffice"].forEach(id=>$(id).innerHTML=offices.map(([id,o])=>`<option value="${id}">${o.number} Procuradoria</option>`).join(""));$("#sessionOrgan").innerHTML=organs.map(o=>`<option value="${o.id}">${o.name}</option>`).join("")}
async function loadVacations(){const y=$("#publicYear").value;const rows=await api("/vacations?year="+y);$("#vacTable").innerHTML=`<table><thead><tr><th>Procuradoria</th><th>Início</th><th>Fim</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.office}</td><td>${fmt(r.start)}</td><td>${fmt(r.end)}</td><td><button onclick="delVac(${r.id})">Excluir</button></td></tr>`).join("")}</tbody></table>`}
window.delVac=async id=>{await api("/vacations/"+id,{method:"DELETE"});await loadVacations();await loadPublic()};
async function loadSessions(){const rows=await api("/sessions?year="+$("#publicYear").value);$("#sessionTable").innerHTML=`<table><thead><tr><th>Data</th><th>Órgão</th><th>Nominal</th><th>Efetiva</th><th>Situação</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmt(r.date)}</td><td>${organs.find(o=>o.id===r.organ_id)?.name||r.organ_id}</td><td>${officeMap.get(r.nominal_office_id)?.number||r.nominal_office_id}</td><td>${officeMap.get(r.effective_office_id)?.number||"Pendente"}</td><td>${r.status}</td></tr>`).join("")}</tbody></table>`}
async function loadSubs(){const rows=await api("/substitutions");$("#subTable").innerHTML=`<table><thead><tr><th>Titular</th><th>Substituta</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${officeMap.get(r.office_id)?.number}</td><td>${officeMap.get(r.substitute_office_id)?.number}</td></tr>`).join("")}</tbody></table>`}
async function loadAudit(){try{const rows=await api("/audit?limit=100");$("#auditTable").innerHTML=`<table><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>Detalhes</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString("pt-BR")}</td><td>${r.action}</td><td>${r.entity}</td><td>${r.details||""}</td></tr>`).join("")}</tbody></table>`}catch{$("#auditTable").textContent="Auditoria disponível apenas ao administrador."}}
async function loadSchedule(){const rows=await api("/schedule-config");const map=new Map(rows.map(r=>[r.organ_id,r]));const days=["Segunda","Terça","Quarta","Quinta","Sexta","Sábado","Domingo"];$("#scheduleConfig").innerHTML=`<table><thead><tr><th>Órgão</th><th>Dia</th><th></th></tr></thead><tbody>${organs.map(o=>{const cur=map.get(o.id);return `<tr><td>${o.name}</td><td><select id="weekday-${o.id}">${days.map((d,i)=>`<option value="${i}" ${cur&&cur.weekday===i?"selected":""}>${d}</option>`).join("")}</select></td><td><button onclick="saveSchedule(${o.id})">Salvar</button></td></tr>`}).join("")}</tbody></table>`}
window.saveSchedule=async id=>{await api(`/schedule-config?organ_id=${id}&weekday=${$("#weekday-"+id).value}&active=true`,{method:"POST"});await loadSchedule()};
async function loadUsers(){const rows=await api("/users");$("#userTable").innerHTML=`<table><thead><tr><th>Usuário</th><th>Perfil</th><th>Ativo</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.username}</td><td>${r.role}</td><td>${r.active?"Sim":"Não"}</td></tr>`).join("")}</tbody></table>`}


$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData();fd.append("username",$("#username").value);fd.append("password",$("#password").value);try{const r=await fetch(API+"/auth/login",{method:"POST",body:fd});if(!r.ok)throw new Error("Usuário ou senha inválidos");const d=await r.json();token=d.access_token;localStorage.setItem("mpce_token",token);await bootAdmin()}catch(e){$("#loginMsg").className="error";$("#loginMsg").textContent=e.message}});
$("#vacForm").addEventListener("submit",async e=>{e.preventDefault();try{await api(`/vacations?office_id=${$("#vacOffice").value}&start=${$("#vacStart").value}&end=${$("#vacEnd").value}`,{method:"POST"});$("#vacMsg").className="ok";$("#vacMsg").textContent="Período incluído.";await loadVacations();await loadPublic()}catch(e){$("#vacMsg").className="error";$("#vacMsg").textContent=e.message}});
$("#sessionForm").addEventListener("submit",async e=>{e.preventDefault();await api(`/sessions?organ_id=${$("#sessionOrgan").value}&session_date=${$("#sessionDate").value}&nominal_office_id=${$("#sessionOffice").value}&note=${encodeURIComponent($("#sessionNote").value)}`,{method:"POST"});await loadSessions();await loadPublic()});
$("#subForm").addEventListener("submit",async e=>{e.preventDefault();await api(`/substitutions?office_id=${$("#subOffice").value}&substitute_office_id=${$("#substituteOffice").value}`,{method:"POST"});await loadSubs()});
$("#generateYear").addEventListener("click",async()=>{try{const r=await api(`/sessions/generate?year=${$("#publicYear").value}`,{method:"POST"});$("#generateMsg").className="ok";$("#generateMsg").textContent=`Geradas ${r.generated} sessões; ${r.skipped} datas excluídas.`;await loadSessions();await loadPublic()}catch(e){$("#generateMsg").className="error";$("#generateMsg").textContent=e.message}});
$("#userForm").addEventListener("submit",async e=>{e.preventDefault();await api(`/users?username=${encodeURIComponent($("#newUsername").value)}&password=${encodeURIComponent($("#newPassword").value)}&role=${$("#newRole").value}`,{method:"POST"});e.target.reset();await loadUsers()});
$("#logout").addEventListener("click",()=>{localStorage.removeItem("mpce_token");location.reload()});$("#publicYear").addEventListener("change",async()=>{await loadPublic();if(token){loadVacations();loadSessions()}});
document.querySelectorAll("[data-tab]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.hidden=true);$("#"+b.dataset.tab).hidden=false}));
loadPublic();bootAdmin();