const publicOffices=["13ª","20ª","26ª","8ª","14ª","52ª","17ª","43ª","21ª"];
const privateOffices=["36ª","40ª","53ª","39ª","30ª","4ª","1ª","38ª","51ª","46ª","57ª","56ª","25ª","34ª","45ª","22ª","27ª","32ª"];
const allOffices=[...publicOffices,...privateOffices];
const organs=[
{id:"cam-pub-1",name:"1ª Câmara de Direito Público",area:"Direito Público",type:"Câmara",offices:["13ª","20ª","26ª"]},
{id:"cam-pub-2",name:"2ª Câmara de Direito Público",area:"Direito Público",type:"Câmara",offices:["8ª","14ª","52ª"]},
{id:"cam-pub-3",name:"3ª Câmara de Direito Público",area:"Direito Público",type:"Câmara",offices:["17ª","43ª","21ª"],officeStatus:{"21ª":"Convocado — a ser preenchido"}},
{id:"sec-pub",name:"Seção de Direito Público",area:"Direito Público",type:"Seção",offices:publicOffices},
{id:"cam-priv-1",name:"1ª Câmara de Direito Privado",area:"Direito Privado",type:"Câmara",offices:["36ª","40ª","53ª"]},
{id:"cam-priv-2",name:"2ª Câmara de Direito Privado",area:"Direito Privado",type:"Câmara",offices:["39ª","30ª","4ª"]},
{id:"cam-priv-3",name:"3ª Câmara de Direito Privado",area:"Direito Privado",type:"Câmara",offices:["1ª","38ª","51ª"]},
{id:"cam-priv-4",name:"4ª Câmara de Direito Privado",area:"Direito Privado",type:"Câmara",offices:["46ª","57ª","56ª"]},
{id:"cam-priv-5",name:"5ª Câmara de Direito Privado",area:"Direito Privado",type:"Câmara",offices:["25ª","34ª","45ª"]},
{id:"cam-priv-6",name:"6ª Câmara de Direito Privado",area:"Direito Privado",type:"Câmara",offices:["22ª","27ª","32ª"]},
{id:"sec-priv",name:"Seção de Direito Privado",area:"Direito Privado",type:"Seção",offices:privateOffices},
{id:"turma-priv-1",name:"1ª Turma de Direito Privado",area:"Direito Privado",type:"Turma",offices:privateOffices},
{id:"turma-priv-2",name:"2ª Turma de Direito Privado",area:"Direito Privado",type:"Turma",offices:privateOffices},
{id:"nucleo-4",name:"Núcleo de Justiça 4.0",area:"Núcleo 4.0",type:"Núcleo",offices:allOffices}
];
const chambers=organs;
const primaryMap=new Map();organs.filter(o=>o.type==="Câmara").forEach(g=>g.offices.forEach(o=>{if(!primaryMap.has(o))primaryMap.set(o,g)}));
const offices=allOffices.map(office=>{const p=primaryMap.get(office);return{office,chamber:p?.name||"",primaryOrganId:p?.id||"",area:publicOffices.includes(office)?"Direito Público":"Direito Privado",status:office==="21ª"?"Convocado — a ser preenchido":""}});
let vacations=JSON.parse(localStorage.getItem("escala_tjce_v3")||"[]");
let tjceScale=JSON.parse(localStorage.getItem("escala_tjce_v4_tjce")||"[]");
let substitutions=JSON.parse(localStorage.getItem("escala_tjce_v4_subs")||"[]");
let sessionConfig=JSON.parse(localStorage.getItem("escala_tjce_v5_sessions")||"{}");
let exclusions=JSON.parse(localStorage.getItem("escala_tjce_v5_exclusions")||"[]");
const $=s=>document.querySelector(s);const year=()=>Number($("#year").value);
const parseDate=s=>{const [y,m,d]=s.split("-").map(Number);return new Date(Date.UTC(y,m-1,d))};
const fmt=s=>s?parseDate(s).toLocaleDateString("pt-BR",{timeZone:"UTC"}):"—";
const days=(a,b)=>Math.floor((parseDate(b)-parseDate(a))/86400000)+1;
const overlaps=(a1,a2,b1,b2)=>parseDate(a1)<=parseDate(b2)&&parseDate(b1)<=parseDate(a2);
const byOffice=o=>offices.find(x=>x.office===o);const byOrgan=id=>organs.find(x=>x.id===id)||organs.find(x=>x.name===id);
const organFor=x=>byOrgan(x.organId)||primaryMap.get(x.office)||organs[0];
const current=()=>vacations.filter(v=>parseDate(v.start).getUTCFullYear()===year());
function save(){localStorage.setItem("escala_tjce_v3",JSON.stringify(vacations));localStorage.setItem("escala_tjce_v4_tjce",JSON.stringify(tjceScale));localStorage.setItem("escala_tjce_v4_subs",JSON.stringify(substitutions));localStorage.setItem("escala_tjce_v5_sessions",JSON.stringify(sessionConfig));localStorage.setItem("escala_tjce_v5_exclusions",JSON.stringify(exclusions))}
function badge(t,c){return`<span class="badge ${c}">${t}</span>`}function officeDays(o){return current().filter(v=>v.office===o).reduce((s,v)=>s+days(v.start,v.end),0)}function officePeriods(o){return current().filter(v=>v.office===o)}
function organOptions(all=true){return(all?'<option value="all">Todos os órgãos</option>':'')+organs.map(o=>`<option value="${o.id}">${o.name}</option>`).join("")}
function filterOrgans(v){return v==="all"?organs:organs.filter(o=>o.id===v||o.name===v)}
function validate(office,start,end,ignore=null){const issues=[],warnings=[];const d=days(start,end);if(parseDate(start).getUTCFullYear()!==year())issues.push(`O início deve ocorrer em ${year()}.`);if(d<10)issues.push("Período inferior a 10 dias.");if(d>30)issues.push("Período superior a 30 dias.");const own=current().filter(v=>v.office===office&&v.id!==ignore);if(own.length>=6)issues.push("A Procuradoria já possui 6 períodos cadastrados.");if(own.some(v=>overlaps(start,end,v.start,v.end)))issues.push("Há sobreposição com outro período da mesma Procuradoria.");const total=own.reduce((s,v)=>s+days(v.start,v.end),0)+d;if(total>60)issues.push("O total anual ultrapassa 60 dias.");const p=primaryMap.get(office);if(p){const c=new Set(current().filter(v=>v.id!==ignore&&v.office!==office&&p.offices.includes(v.office)&&overlaps(start,end,v.start,v.end)).map(v=>v.office));if((1+c.size)/p.offices.length>0.5)issues.push(`Conflito: ${1+c.size} de ${p.offices.length} Procuradorias da Câmara ficariam simultaneamente em férias.`)}let sp=0;[...own,{start,end}].forEach(v=>{let d0=parseDate(v.start),de=parseDate(v.end);while(d0<=de){if([0,6,11].includes(d0.getUTCMonth()))sp++;d0=new Date(d0.getTime()+86400000)}});if(sp>30)warnings.push("Mais de 30 dias recaem em janeiro, julho e dezembro.");return{issues,warnings,total,d}}
function populate(){const officeOpts=offices.sort((a,b)=>parseInt(a.office)-parseInt(b.office)).map(o=>`<option value="${o.office}">${o.office} Procuradoria${o.status?" ("+o.status+")":""} — ${o.chamber}</option>`).join("");["#vacOffice","#subOffice","#substituteOffice","#tjceOffice"].forEach(id=>{if($(id))$(id).innerHTML=officeOpts});["#dashFilter","#calendarFilter","#tjceFilter","#conflictFilter","#consolidatedFilter","#publicChamberFilter"].forEach(id=>{if($(id))$(id).innerHTML=organOptions(true)});if($("#chamberPanelFilter"))$("#chamberPanelFilter").innerHTML=organOptions(false);if($("#exclusionChamber"))$("#exclusionChamber").innerHTML=organOptions(false);const form=$("#tjceForm");if(form&&!$("#tjceOrgan")){const label=document.createElement("label");label.innerHTML='Órgão do TJCE<select id="tjceOrgan" required></select>';form.insertBefore(label,form.firstElementChild)}if($("#tjceOrgan"))$("#tjceOrgan").innerHTML=organOptions(false)}
function selectedOffices(filter){return[...new Set(filterOrgans($(filter).value).flatMap(o=>o.offices))]}
function renderDashboard(){const data=offices.filter(o=>selectedOffices("#dashFilter").includes(o.office));$("#kpiOffices").textContent=offices.length;$("#kpiPeriods").textContent=current().length;$("#kpiWithVac").textContent=new Set(current().map(v=>v.office)).size;$("#kpiConflicts").textContent=current().filter(v=>validate(v.office,v.start,v.end,v.id).issues.length).length;$("#dashboardTable").innerHTML=`<table><thead><tr><th>Procuradoria</th><th>Vinculação principal</th><th>Períodos</th><th>Total</th><th>Situação</th></tr></thead><tbody>${data.map(o=>{const ps=officePeriods(o.office),t=officeDays(o.office);return`<tr><td><strong>${o.office} Procuradoria</strong>${o.status?`<br><small>${o.status}</small>`:""}</td><td>${o.chamber}</td><td>${ps.map(v=>`${fmt(v.start)} a ${fmt(v.end)}`).join("<br>")||"—"}</td><td>${t}</td><td>${t===60?badge("60 dias","ok"):t<60?badge(`${60-t} dias pendentes`,"warn"):badge("Acima de 60","danger")}</td></tr>`}).join("")}</tbody></table>`}
function renderVacations(){const rows=current().sort((a,b)=>parseDate(a.start)-parseDate(b.start)).map(v=>{const info=byOffice(v.office),val=validate(v.office,v.start,v.end,v.id);const st=val.issues.length?badge("Conflito","danger"):val.warnings.length?badge("Atenção","warn"):badge("Regular","ok");return`<tr><td>${v.office} Procuradoria</td><td>${info.chamber}</td><td>${fmt(v.start)}</td><td>${fmt(v.end)}</td><td>${days(v.start,v.end)}</td><td>${st}<br><small>${[...val.issues,...val.warnings].join(" ")}</small></td><td><button class="danger-btn" data-del="${v.id}" type="button">Excluir</button></td></tr>`}).join("");$("#vacationTable").innerHTML=`<table><thead><tr><th>Procuradoria</th><th>Vinculação principal</th><th>Início</th><th>Fim</th><th>Dias</th><th>Validação</th><th></th></tr></thead><tbody>${rows}</tbody></table>`;document.querySelectorAll("[data-del]").forEach(b=>b.addEventListener("click",()=>{vacations=vacations.filter(v=>v.id!==Number(b.dataset.del));save();renderAll()}))}
function vacationOnDate(o,d){return current().find(v=>v.office===o&&parseDate(v.start)<=parseDate(d)&&parseDate(d)<=parseDate(v.end))||null}function subFor(o){const s=substitutions.find(x=>x.office===o);return s?s.substitute:""}function subAvail(s,d){return!!s&&!vacationOnDate(s,d)}
function consolidatedRows(){return tjceScale.filter(x=>parseDate(x.date).getUTCFullYear()===year()).sort((a,b)=>parseDate(a.date)-parseDate(b.date)).map(x=>{const org=organFor(x),vac=vacationOnDate(x.office,x.date);let effective=x.office,situation="Titular disponível",severity="ok";if(vac){const sub=subFor(x.office);if(sub&&subAvail(sub,x.date)){effective=sub;situation="Substituição aplicada";severity="warn"}else if(sub){effective=sub;situation="Conflito: substituto indisponível";severity="danger"}else{effective="";situation="Conflito: sem substituto definido";severity="danger"}}return{date:x.date,organId:org.id,chamber:org.name,area:org.area,nominal:x.office,effective,situation,severity,origin:x.generated?"Automática":"Manual",note:x.note||""}})}
function renderTJCE(){const ids=filterOrgans($("#tjceFilter").value).map(o=>o.id);const rows=consolidatedRows().filter(r=>$("#tjceFilter").value==="all"||ids.includes(r.organId)).map(r=>`<tr><td>${fmt(r.date)}</td><td>${r.chamber}</td><td><strong>${r.nominal} Procuradoria</strong></td><td>${r.origin}</td><td>${r.note||"—"}</td><td>${badge(r.situation,r.severity)}</td><td>${r.effective?r.effective+" Procuradoria":"Pendente"}</td><td><button class="danger-btn" data-tjce-del="${r.date}-${r.organId}-${r.nominal}" type="button">Excluir</button></td></tr>`).join("");$("#tjceTable").innerHTML=`<table><thead><tr><th>Data</th><th>Órgão</th><th>Procuradoria nominal</th><th>Origem</th><th>Observação</th><th>Situação</th><th>Atuação efetiva</th><th></th></tr></thead><tbody>${rows}</tbody></table>`;document.querySelectorAll("[data-tjce-del]").forEach((b,i)=>b.addEventListener("click",()=>{const visible=consolidatedRows().filter(r=>$("#tjceFilter").value==="all"||ids.includes(r.organId));const r=visible[i];tjceScale=tjceScale.filter(x=>!(x.date===r.date&&(x.organId||organFor(x).id)===r.organId&&x.office===r.nominal));save();renderAll()}))}
function renderConsolidated(){const ids=filterOrgans($("#consolidatedFilter").value).map(o=>o.id);const rows=consolidatedRows().filter(r=>$("#consolidatedFilter").value==="all"||ids.includes(r.organId)).map(r=>`<tr><td>${fmt(r.date)}</td><td>${r.chamber}</td><td>${r.nominal} Procuradoria</td><td>${r.origin}</td><td>${r.note||"—"}</td><td>${badge(r.situation,r.severity)}</td><td>${r.effective?r.effective+" Procuradoria":"Pendente"}</td></tr>`).join("");$("#consolidatedTable").innerHTML=`<table><thead><tr><th>Data</th><th>Órgão</th><th>Procuradoria nominal</th><th>Origem</th><th>Observação</th><th>Situação</th><th>Atuação efetiva</th></tr></thead><tbody>${rows}</tbody></table>`}
const weekdays=[{value:"",label:"Não gerar"},{value:"1",label:"Segunda-feira"},{value:"2",label:"Terça-feira"},{value:"3",label:"Quarta-feira"},{value:"4",label:"Quinta-feira"},{value:"5",label:"Sexta-feira"}];const iso=d=>`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`;
function renderSessionConfig(){const rows=organs.map(o=>`<tr><td>${o.area}</td><td>${o.name}</td><td>${o.type}</td><td><select class="session-select" data-session-chamber="${o.id}">${weekdays.map(w=>`<option value="${w.value}" ${String(sessionConfig[o.id]||"")===w.value?"selected":""}>${w.label}</option>`).join("")}</select></td></tr>`).join("");$("#sessionConfigTable").innerHTML=`<table><thead><tr><th>Área</th><th>Órgão</th><th>Tipo</th><th>Dia semanal da sessão</th></tr></thead><tbody>${rows}</tbody></table>`;document.querySelectorAll("[data-session-chamber]").forEach(s=>s.addEventListener("change",()=>{sessionConfig[s.dataset.sessionChamber]=s.value;save()}))}
function renderExclusions(){const rows=exclusions.filter(x=>parseDate(x.date).getUTCFullYear()===year()).map(x=>`<tr><td>${fmt(x.date)}</td><td>${byOrgan(x.organId||x.chamber)?.name||x.chamber}</td><td>${x.reason||"—"}</td><td><button class="danger-btn" data-ex-del="${x.id}">Excluir</button></td></tr>`).join("");$("#exclusionTable").innerHTML=`<table><thead><tr><th>Data</th><th>Órgão</th><th>Motivo</th><th></th></tr></thead><tbody>${rows}</tbody></table>`;document.querySelectorAll("[data-ex-del]").forEach(b=>b.addEventListener("click",()=>{exclusions=exclusions.filter(x=>x.id!==Number(b.dataset.exDel));save();renderAll()}))}
function renderRotation(){ $("#rotationTable").innerHTML=`<table><thead><tr><th>Órgão</th><th>Sequência nominal do rodízio</th></tr></thead><tbody>${organs.map(o=>`<tr><td>${o.name}</td><td class="rotation-seq">${o.offices.join(" → ")}</td></tr>`).join("")}</tbody></table>`}
function generateAnnualScale(){const configured=organs.filter(o=>String(sessionConfig[o.id]||"")!=="");const msg=$("#generatorMessage");if(!configured.length){msg.className="message show warn";msg.textContent="Defina ao menos um dia semanal de sessão antes de gerar a escala.";return}tjceScale=tjceScale.filter(x=>!(x.generated&&parseDate(x.date).getUTCFullYear()===year()));let gen=0,skip=0;configured.forEach(o=>{const weekday=Number(sessionConfig[o.id]);let idx=0,d=new Date(Date.UTC(year(),0,1)),last=new Date(Date.UTC(year(),11,31));while(d<=last){if(d.getUTCDay()===weekday){const date=iso(d);if(exclusions.some(x=>(x.organId||x.chamber)===o.id&&x.date===date))skip++;else{tjceScale.push({id:Date.now()+gen,organId:o.id,office:o.offices[idx%o.offices.length],date,note:"Rodízio automático",generated:true});gen++;idx++}}d=new Date(d.getTime()+86400000)}});save();renderAll();msg.className="message show ok";msg.textContent=`Escala anual gerada: ${gen} sessões incluídas e ${skip} datas excluídas.`}
function renderChambers(){ $("#chambersTable").innerHTML=`<table><thead><tr><th>Área</th><th>Órgão do TJCE</th><th>Tipo</th><th>Procuradorias em rodízio</th></tr></thead><tbody>${organs.map(o=>`<tr><td>${o.area}</td><td>${o.name}</td><td>${o.type}</td><td>${o.offices.map(p=>p+" Procuradoria"+(o.officeStatus&&o.officeStatus[p]?" ("+o.officeStatus[p]+")":"")).join(" • ")}</td></tr>`).join("")}</tbody></table>`}
function renderCalendar(){const data=offices.filter(o=>selectedOffices("#calendarFilter").includes(o.office));const months=["JAN","FEV","MAR","ABR","MAI","JUN","JUL","AGO","SET","OUT","NOV","DEZ"];$("#calendarTable").innerHTML=`<table><thead><tr><th>Procuradoria</th>${months.map(m=>`<th>${m}</th>`).join("")}</tr></thead><tbody>${data.map(o=>`<tr><td><strong>${o.office}</strong><br><small>${o.chamber}</small></td>${months.map((_,i)=>`<td class="month">${current().filter(v=>v.office===o.office&&parseDate(v.start).getUTCMonth()<=i&&parseDate(v.end).getUTCMonth()>=i).map(v=>`<span class="chip">${fmt(v.start)}–${fmt(v.end)}</span>`).join("")}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function renderSubstitutions(){const rows=offices.map(o=>{const s=substitutions.find(x=>x.office===o.office);return`<tr><td>${o.office} Procuradoria</td><td>${o.chamber}</td><td>${s?s.substitute+" Procuradoria":"—"}</td><td>${s?`<button class="danger-btn" data-sub-del="${o.office}">Excluir</button>`:""}</td></tr>`}).join("");$("#subTable").innerHTML=`<table><thead><tr><th>Titular</th><th>Vinculação principal</th><th>Substituta</th><th></th></tr></thead><tbody>${rows}</tbody></table>`;document.querySelectorAll("[data-sub-del]").forEach(b=>b.addEventListener("click",()=>{substitutions=substitutions.filter(x=>x.office!==b.dataset.subDel);save();renderAll()}))}
function renderChamberPanel(){const org=byOrgan($("#chamberPanelFilter").value);if(!org)return;const vacs=current().filter(v=>org.offices.includes(v.office));const sessions=tjceScale.filter(x=>parseDate(x.date).getUTCFullYear()===year()&&(x.organId===org.id||(!x.organId&&org.offices.includes(x.office))));$("#chamberPanelContent").innerHTML=`<div class="chamber-summary"><div class="mini-card"><span>Procuradorias</span><strong>${org.offices.length}</strong></div><div class="mini-card"><span>Períodos de férias</span><strong>${vacs.length}</strong></div><div class="mini-card"><span>Sessões TJCE</span><strong>${sessions.length}</strong></div><div class="mini-card"><span>Tipo</span><strong>${org.type}</strong></div></div><h3 class="section-title">Férias</h3><table><thead><tr><th>Procuradoria</th><th>Períodos</th><th>Total</th></tr></thead><tbody>${org.offices.map(o=>`<tr><td>${o} Procuradoria</td><td>${officePeriods(o).map(v=>fmt(v.start)+" a "+fmt(v.end)).join("<br>")||"—"}</td><td>${officeDays(o)}</td></tr>`).join("")}</tbody></table>`}
function renderConflicts(){$("#conflictTable").innerHTML="<p>Os conflitos por férias continuam sendo apurados pela Câmara de vinculação principal de cada Procuradoria.</p>"}
function renderPublicDashboard(){const rows=consolidatedRows().filter(r=>($("#publicAreaFilter").value==="all"||r.area===$("#publicAreaFilter").value)&&($("#publicChamberFilter").value==="all"||r.organId===$("#publicChamberFilter").value)&&($("#publicMonthFilter").value==="all"||parseDate(r.date).getUTCMonth()===Number($("#publicMonthFilter").value)));$("#publicYearLabel").textContent=year();$("#publicKpiSessions").textContent=rows.length;$("#publicKpiChambers").textContent=new Set(rows.map(r=>r.chamber)).size;$("#publicKpiSubs").textContent=rows.filter(r=>r.situation==="Substituição aplicada").length;$("#publicKpiPending").textContent=rows.filter(r=>r.severity==="danger").length;$("#publicAgenda").innerHTML=rows.length?`<table><thead><tr><th>Data</th><th>Órgão</th><th>Procuradoria nominal</th><th>Situação</th><th>Atuação efetiva</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmt(r.date)}</td><td>${r.chamber}</td><td>${r.nominal} Procuradoria</td><td>${badge(r.situation,r.severity)}</td><td>${r.effective?r.effective+" Procuradoria":"Pendente"}</td></tr>`).join("")}</tbody></table>`:"<p>Nenhuma atuação cadastrada para os filtros selecionados.</p>";$("#publicChamberSummary").innerHTML="";$("#publicCalendar").innerHTML="";$("#publicVacations").innerHTML=""}
function syncPublicChamberOptions(){const area=$("#publicAreaFilter").value,current=$("#publicChamberFilter").value||"all";const filtered=area==="all"?organs:organs.filter(o=>o.area===area);$("#publicChamberFilter").innerHTML='<option value="all">Todos os órgãos</option>'+filtered.map(o=>`<option value="${o.id}">${o.name}</option>`).join("");if([...$("#publicChamberFilter").options].some(o=>o.value===current))$("#publicChamberFilter").value=current}
function renderAll(){syncPublicChamberOptions();renderPublicDashboard();renderDashboard();renderChamberPanel();renderConflicts();renderConsolidated();renderVacations();renderScale();renderSessionConfig();renderExclusions();renderRotation();renderTJCE();renderSubstitutions();renderCalendar();renderChambers()}
$("#vacationForm").addEventListener("submit",e=>{e.preventDefault();const office=$("#vacOffice").value,start=$("#vacStart").value,end=$("#vacEnd").value,msg=$("#message");if(!start||!end||parseDate(end)<parseDate(start)){msg.className="message show danger";msg.textContent="Informe um intervalo válido.";return}vacations.push({id:Date.now(),office,start,end});save();renderAll();msg.className="message show ok";msg.textContent="Período incluído."});
$("#tjceForm").addEventListener("submit",e=>{e.preventDefault();const office=$("#tjceOffice").value,date=$("#tjceDate").value,note=$("#tjceNote").value.trim(),organId=$("#tjceOrgan")?.value||byOffice(office).primaryOrganId;if(!date)return;tjceScale.push({id:Date.now(),organId,office,date,note,generated:false});save();renderAll();$("#tjceMessage").className="message show ok";$("#tjceMessage").textContent="Atuação adicionada."});
$("#subForm").addEventListener("submit",e=>{e.preventDefault();const office=$("#subOffice").value,sub=$("#substituteOffice").value;if(office===sub)return;substitutions=substitutions.filter(x=>x.office!==office);substitutions.push({office,substitute:sub});save();renderAll()});
$("#exclusionForm").addEventListener("submit",e=>{e.preventDefault();const organId=$("#exclusionChamber").value,date=$("#exclusionDate").value,reason=$("#exclusionReason").value.trim();exclusions.push({id:Date.now(),organId,chamber:organId,date,reason});save();renderAll()});
$("#generateAnnualBtn").addEventListener("click",generateAnnualScale);$("#generateBtn").addEventListener("click",renderScale);["#dashFilter","#calendarFilter","#tjceFilter","#chamberPanelFilter","#conflictFilter","#consolidatedFilter"].forEach(id=>$(id).addEventListener("change",renderAll));$("#year").addEventListener("change",renderAll);$("#printBtn").addEventListener("click",()=>window.print());$("#publicAreaFilter").addEventListener("change",renderAll);$("#publicChamberFilter").addEventListener("change",renderAll);$("#publicMonthFilter").addEventListener("change",renderAll);$("#publicResetFilters").addEventListener("click",()=>{$("#publicAreaFilter").value="all";$("#publicChamberFilter").value="all";$("#publicMonthFilter").value="all";renderAll()});
function downloadCSV(rows,name){const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(";")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("#exportConsolidated").addEventListener("click",()=>downloadCSV([["DATA","ÓRGÃO","PROCURADORIA","SITUAÇÃO"],...consolidatedRows().map(r=>[fmt(r.date),r.chamber,r.nominal,r.situation])],`escala_consolidada_tjce_${year()}.csv`));$("#exportBtn").addEventListener("click",()=>downloadCSV([["DATA","ÓRGÃO","PROCURADORIA","SITUAÇÃO"],...consolidatedRows().map(r=>[fmt(r.date),r.chamber,r.nominal,r.situation])],`escala_tjce_${year()}.csv`));
document.querySelectorAll(".nav").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));btn.classList.add("active");$("#"+btn.dataset.view).classList.add("active")}));
populate();renderAll();